FROM apache/airflow:2.9.0
USER root

# Install OS-level dependencies
RUN apt-get update && apt-get install -y \
    python3-pip \
    python3-dev \
    git \
    && rm -rf /var/lib/apt/lists/*

# Copy custom DAGs and source code
WORKDIR /opt/airflow
COPY dags ./dags
COPY ../etl ../etl
COPY ../training ../training
COPY ../deployment ../deployment

# Install Python dependencies
COPY ../requirements.txt ./requirements.txt
RUN pip install -r requirements.txt

USER airflow
ENTRYPOINT [ "airflow" ]
CMD [ "webserver" ]
